In [1]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

data = fetch_california_housing(as_frame=True)
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

rf_reg = RandomForestRegressor(
    n_estimators      = 200,
    max_depth         = 12,         # ← tune this
    min_samples_split = 5,
    min_samples_leaf  = 2,
    max_features      = 0.6,        # fraction of features
    bootstrap         = True,
    random_state      = 42,
    n_jobs            = -1,
    oob_score         = True        # ← very useful!
)

rf_reg.fit(X_train, y_train)

y_pred = rf_reg.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2   = r2_score(y_test, y_pred)

print(f"RMSE      : {rmse:.3f}   → error ≈ ${rmse*100_000:.0f}")
print(f"R²        : {r2:.3f}")
print(f"OOB score : {rf_reg.oob_score_:.3f}")   # out-of-bag estimate — very handy

RMSE      : 0.521   → error ≈ $52055
R²        : 0.793
OOB score : 0.803

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("Chocolate Sales (2).csv")

In [5]:
df.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184

In [6]:
df.sample(5)

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
2054,Jehu Rudeforth,India,Peanut Butter Cubes,14/04/2023,$31.15,451
908,Curtice Advani,Australia,Caramel Stuffed Bars,14/02/2022,"$9,114.00",140
1818,Madelene Upcott,UK,Raspberry Choco,26/08/2023,"$7,361.93",344
1914,Kelci Walkden,USA,Almond Choco,27/01/2023,"$5,425.24",234
1068,Madelene Upcott,Canada,Milk Bars,26/04/2022,"$3,612.00",82

In [7]:
X = df.iloc[: , : -1]
y = df.iloc[: , -1]

In [ ]:
X = df[[""]]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train , X_test , y_train , y_test = train_test_split(X , y ,random_state=42)

In [10]:
from sklearn.ensemble import RandomForestRegressor
rfr1 = RandomForestRegressor(
   n_estimators      = 200,
    max_depth         = 12,         # ← tune this
    min_samples_split = 5,
    min_samples_leaf  = 2,
    max_features      = 0.6,        # fraction of features
    bootstrap         = True,
    random_state      = 42,
    n_jobs            = -1,
    oob_score         = True 
)

In [11]:
rfr1.fit(X , y)

ValueError: could not convert string to float: 'Jehu Rudeforth'